// Generated by gencpp from file edge_detection/service.msg
// DO NOT EDIT!


#ifndef EDGE_DETECTION_MESSAGE_SERVICE_H
#define EDGE_DETECTION_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <edge_detection/serviceRequest.h>
#include <edge_detection/serviceResponse.h>


namespace edge_detection
{

struct service
{

typedef serviceRequest Request;
typedef serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service
} // namespace edge_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edge_detection::service > {
  static const char* value()
  {
    return "e688705977db0e1d33f518faf3757bce";
  }

  static const char* value(const ::edge_detection::service&) { return value(); }
};

template<>
struct DataType< ::edge_detection::service > {
  static const char* value()
  {
    return "edge_detection/service";
  }

  static const char* value(const ::edge_detection::service&) { return value(); }
};


// service_traits::MD5Sum< ::edge_detection::serviceRequest> should match
// service_traits::MD5Sum< ::edge_detection::service >
template<>
struct MD5Sum< ::edge_detection::serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection::service >::value();
  }
  static const char* value(const ::edge_detection::serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection::serviceRequest> should match
// service_traits::DataType< ::edge_detection::service >
template<>
struct DataType< ::edge_detection::serviceRequest>
{
  static const char* value()
  {
    return DataType< ::edge_detection::service >::value();
  }
  static const char* value(const ::edge_detection::serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edge_detection::serviceResponse> should match
// service_traits::MD5Sum< ::edge_detection::service >
template<>
struct MD5Sum< ::edge_detection::serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection::service >::value();
  }
  static const char* value(const ::edge_detection::serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection::serviceResponse> should match
// service_traits::DataType< ::edge_detection::service >
template<>
struct DataType< ::edge_detection::serviceResponse>
{
  static const char* value()
  {
    return DataType< ::edge_detection::service >::value();
  }
  static const char* value(const ::edge_detection::serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDGE_DETECTION_MESSAGE_SERVICE_H
